name: First Workflow

on: workflow_dispatch

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World!"
      - name: print bye
        run: echo "Good bye!"

